FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    sqlite3 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY app.py index.py resultado.py db_init.py ./

COPY static/ ./static/

RUN python db_init.py

EXPOSE 5000

CMD ["python", "app.py"]